#:schema https://raw.githubusercontent.com/cloudflare/wrangler/main/packages/wrangler/config-schema.json
name = "mpc-conect"
main = "src/worker/index.ts"
compatibility_date = "2024-03-01"



# GITHUB_CLIENT_ID, GITHUB_USERNAME, GITHUB_TOKEN, AUTH_TOKEN, and GITHUB_CLIENT_SECRET 
# should be set via the Cloudflare Dashboard or 'wrangler secret put'

[[kv_namespaces]]
binding = "MCP_CACHE"
id = "98a89168e6304961bd9503d68b029210" # Replace with your KV ID after 'wrangler kv:namespace create MCP_CACHE'

